backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'images/uploads'

collections:
  - label: "Blog"
    name: "blog"
    files:
      - label: 'Posts'
        name: 'posts'
        file: "site/content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Contenuto, name: content, widget: markdown}