backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'src/assets/image/uploads'

collections:
  - name: "blog"
    label: "Blog"
    description: "Upcoming tours and their availability"
    files:
      - label: "Posts"
        name: "posts"
        file: "src/posts.json"
        fields:
          - label: "Post"
            name: "post"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Contenuto", name: "content", widget: "markdown"}